#!/usr/bin/env bash
# 3. Redirection
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
if ! grep -q 'location /redirect_me {' /etc/nginx/sites-available/default; then
    sudo sed -i '/server_name _;/ a\\n        location /redirect_me {\n                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }' /etc/nginx/sites-available/default
fi
sudo service nginx restart
