#!/usr/bin/env bash

count=1
while [ $count -le 20 ]
do
echo "$count"
case $count in
            "3" )
                    echo "bad luck from China"
            ;;
            "8" )
                    echo "bad luck from Japan"
            ;;
            "16" )
                    echo "bad luck from Italy"
            ;;
            esac
        ((count++))
done
