#!/usr/bin/env bash
# print clock.
Hour=0
while [ $Hour -le 12 ]
do
    echo "Hour: $Hour"
    min=1
    while [ $min -le 59 ]
    do
        echo "$min"
        ((min++))
    done
    ((Hour++))
done
